name: kalpas_task
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^3.1.0
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  intl: ^0.19.0
  sqflite: ^2.3.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
          style: normal
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
          style: normal
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
